### ISSUE TITLE
Quality of the video played 

### ISSUE THREAD

**Issue by ssbaval** [darwin-morocho/flutter-meedu-player#2]
Hi - this is a really nice plugin and the animation effects that you have added are so cool ... I wanted to find out if there is anything that can be done to improve the quality of the video. If I dont use this plugin, the video quality is better so I know its nothing wrong with the MP4 file that I am using...

Is there anything basic I'm missing ?

**Comment by darwin-morocho** [comment]
this plugin use the video_player plugin so if you have a bad quality maybe is a problem of video_player so you can check the if the quality 8s the same using the video_player
