### ISSUE TITLE
issues with auto update video_player 0.11.1+4 in build release 

### ISSUE THREAD

**Issue by Joseph-Nathan** [darwin-morocho/flutter-meedu-player#22]
hi there ,
meedu_player update video_player to 0.11.1+4 by herself ,
and now when i trry to build release this issues stop me 

`Running Gradle task 'assembleRelease'...
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+4\android\src\main\ja
va\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:11: error: cannot find symbol
Running Gradle task 'assembleRelease'...
import io.flutter.FlutterInjector;
Running Gradle task 'assembleRelease'...
                 ^
Running Gradle task 'assembleRelease'...
  symbol:   class FlutterInjector
Running Gradle task 'assembleRelease'...
  location: package io.flutter
Running Gradle task 'assembleRelease'...
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+4\android\src\main\ja
va\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
Running Gradle task 'assembleRelease'...
    final FlutterInjector injector = FlutterInjector.instance();
Running Gradle task 'assembleRelease'...
          ^
Running Gradle task 'assembleRelease'...
  symbol:   class FlutterInjector
Running Gradle task 'assembleRelease'...
  location: class VideoPlayerPlugin
Running Gradle task 'assembleRelease'...
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+4\android\src\main\ja
va\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
Running Gradle task 'assembleRelease'...
    final FlutterInjector injector = FlutterInjector.instance();
Running Gradle task 'assembleRelease'...
                                     ^
Running Gradle task 'assembleRelease'...
  symbol:   variable FlutterInjector
Running Gradle task 'assembleRelease'...
  location: class VideoPlayerPlugin
Running Gradle task 'assembleRelease'...
3 errors
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
FAILURE: Build failed with an exception.
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
* What went wrong:
Running Gradle task 'assembleRelease'...
Execution failed for task ':video_player:compileReleaseJavaWithJavac'.
Running Gradle task 'assembleRelease'...
> Compilation failed; see the compiler error output for details.
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
* Try:
Running Gradle task 'assembleRelease'...
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to g
et more log output. Run with --scan to get full insights.
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
* Get more help at https://help.gradle.org
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
BUILD FAILED in 2m 58s
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'... Done                     179.2s (!)
Gradle task assembleRelease failed with exit code 1
`

please help me ,

**Comment by the-meedu-app** [comment]
> hi there ,
> meedu_player update video_player to 0.11.1+4 by herself ,
> and now when i trry to build release this issues stop me
> 
> `Running Gradle task 'assembleRelease'...
> C:\src\flutter.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+4\android\src\main\ja
> va\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:11: error: cannot find symbol
> Running Gradle task 'assembleRelease'...
> import io.flutter.FlutterInjector;
> Running Gradle task 'assembleRelease'...
> ^
> Running Gradle task 'assembleRelease'...
> symbol: class FlutterInjector
> Running Gradle task 'assembleRelease'...
> location: package io.flutter
> Running Gradle task 'assembleRelease'...
> C:\src\flutter.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+4\android\src\main\ja
> va\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
> Running Gradle task 'assembleRelease'...
> final FlutterInjector injector = FlutterInjector.instance();
> Running Gradle task 'assembleRelease'...
> ^
> Running Gradle task 'assembleRelease'...
> symbol: class FlutterInjector
> Running Gradle task 'assembleRelease'...
> location: class VideoPlayerPlugin
> Running Gradle task 'assembleRelease'...
> C:\src\flutter.pub-cache\hosted\pub.dartlang.org\video_player-0.11.1+4\android\src\main\ja
> va\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java:77: error: cannot find symbol
> Running Gradle task 'assembleRelease'...
> final FlutterInjector injector = FlutterInjector.instance();
> Running Gradle task 'assembleRelease'...
> ^
> Running Gradle task 'assembleRelease'...
> symbol: variable FlutterInjector
> Running Gradle task 'assembleRelease'...
> location: class VideoPlayerPlugin
> Running Gradle task 'assembleRelease'...
> 3 errors
> Running Gradle task 'assembleRelease'...
> 
> Running Gradle task 'assembleRelease'...
> FAILURE: Build failed with an exception.
> Running Gradle task 'assembleRelease'...
> 
> Running Gradle task 'assembleRelease'...
> 
> * What went wrong:
>   Running Gradle task 'assembleRelease'...
>   Execution failed for task ':video_player:compileReleaseJavaWithJavac'.
>   Running Gradle task 'assembleRelease'...
> 
> > Compilation failed; see the compiler error output for details.
> > Running Gradle task 'assembleRelease'...
> 
> Running Gradle task 'assembleRelease'...
> 
> * Try:
>   Running Gradle task 'assembleRelease'...
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to g
>   et more log output. Run with --scan to get full insights.
>   Running Gradle task 'assembleRelease'...
> 
> Running Gradle task 'assembleRelease'...
> 
> * Get more help at https://help.gradle.org
>   Running Gradle task 'assembleRelease'...
> 
> Running Gradle task 'assembleRelease'...
> BUILD FAILED in 2m 58s
> Running Gradle task 'assembleRelease'...
> 
> Running Gradle task 'assembleRelease'... Done 179.2s (!)
> Gradle task assembleRelease failed with exit code 1
> `
> 
> please help me ,

Try running the `flutter clean` command or you can override the video_player dependency and use a previous version https://stackoverflow.com/questions/23031384/how-to-specify-dependency-overrides-in-pubspec-yaml

**Comment by Joseph-Nathan** [comment]
it work by set video_player in pubspec.yaml
