### ISSUE TITLE
Custom HTTP headers

### ISSUE THREAD

**Issue by willsalasare** [darwin-morocho/flutter-meedu-player#26]

**Comment by the-meedu-app** [comment]
> _No description provided._

please add more information

**Comment by willsalasare** [comment]
Podrías agregar headers HTTP por favor? Estaría increíble, por ejemplo, headers:{'authorization':'Bearer token'}

**Comment by darwin-morocho** [comment]
> Podrías agregar headers HTTP por favor? Estaría increíble, por ejemplo, headers:{'authorization':'Bearer token'}

Hi @willsalasare this feature is not possible because the official video_player plugin does not support headers.
