### ISSUE TITLE
How to use the plugin with say a file on Google Drive

### ISSUE THREAD

**Issue by alexda12** [darwin-morocho/flutter-meedu-player#3]
Thanks for this plugin - the UI is so nice.

I have a large MP4 (180MB) - I cannot find a way to use your plugin to stream this from say Onedrive or Google Drive or even YouTube - I get an error - FAILED TO LOAD VIDEO ? I'm assuming its because the LINK you get with these does not point to a specific file with an extension of MP4 but there is no way to create such a link.

My question therefore - how can we use this plugin with movies that are not bundled with the app in assets ?

**Comment by darwin-morocho** [comment]
this plugin use the official video_player package so if the official package does not support these feature this plugin too.
