### ISSUE TITLE
Support HLS Multi-Audio

### ISSUE THREAD

**Issue by Joseph-Nathan** [darwin-morocho/flutter-meedu-player#31]
so that we can proved data Source for audio to replace a video audio ,
thanks bro for your beauty package .

**Comment by darwin-morocho** [comment]
> so that we can proved data Source for audio to replace a video audio ,
> thanks bro for your beauty package .

hi @Joseph-Nathan  this plugin use the official video_player plugin so if video_player doesn't support this feature this plugin too.
