### ISSUE TITLE
How to set fitting on video?

### ISSUE THREAD

**Issue by YaarPatandarAA** [darwin-morocho/flutter-meedu-player#35]
First of all I would like to **thank you** for creating this plugin. I tired to achieve what this plugin is achieving using other video plugins but they all required me to use the player as a widget.

My use case is just playing the video in fullscreen and exit back to the widget I was at when full screen is closed. This plugin helped me do this with ease. **Thank you very much for development work on this plugin and this niche feature.**

ISSUE:
I am trying to scale the video to fit the entire screen. The controls scale the entire screen but the video has black bars on the left and right side. In the plugin `better_player` I used a configuration setting they had set up. 
I used `BoxFit.<my_choice_of_fitting>` and that would scale the video to what ever my choice was.

I do see in the example you say to use `AspectRatio`, however that is around the `MeeduVideoPlayer` widget. In my use case I do not use the `MeeduVideoPlayer`.

MY WORKWROUND:
As of right now I downloaded the plugin and am using it locally and have changed the following.

```
...
AspectRatio(
    aspectRatio: _.videoPlayerController.value.aspectRatio,
    child: VideoPlayer(_.videoPlayerController),
),
...
```

and I have changed it to

```
...
Center(
    child: Container(
        width: double.infinity,
        height: double.infinity,
        child: FittedBox(
            fit: BoxFit.<my_choice_of_fitting>,
            child: SizedBox(
                width: _.videoPlayerController.value.size?.width ?? 0,
                height: _.videoPlayerController.value.size?.height ?? 0,
                child: VideoPlayer(_.videoPlayerController),
            ),
        ),
    ),
),
...
```

**Comment by darwin-morocho** [comment]
hi @YaarPatandarAA you can check this PR https://github.com/darwin-morocho/flutter-meedu-player/pull/34 I will check it tomorrow and if everything is ok i will merge it

**Comment by YaarPatandarAA** [comment]
@darwin-morocho Thank you for pointing me towards #34 this works for me

- I would however suggest adding one more fitting size (`BoxFit.fill`).

```
/// Toggle Change the videofit accordingly
  void toggleVideoFit() {
    // _videoFit.value = _videoFit.value == BoxFit.contain ? BoxFit.cover : BoxFit.contain;
    if(_videoFit.value == BoxFit.contain) _videoFit.value = BoxFit.cover;
    else if(_videoFit.value == BoxFit.cover) _videoFit.value = BoxFit.fill;
    else _videoFit.value = BoxFit.contain;
  }
```
- Additionally the resize icon is smaller than the other icons, I increased it by 2 and it therefore seemed to be similar size with the others around it.
