### ISSUE TITLE
Fullscreen landscape

### ISSUE THREAD

**Issue by alakreasi** [darwin-morocho/flutter-meedu-player#4]
How do I configure automatic fullscreen landscape?
I tried the example, but all video portraits

Thank you

**Comment by alakreasi** [comment]
This problem is resolved when I delete the device orientation on meedu_fullscreen_player.dart.
Suggestions to add loading when connection is slow and lost.

**Comment by darwin-morocho** [comment]
Some videos in fullscreen mode requires portrait. So yo can listen the player events and detect when the player changes to fullscreen and rotate the device to lanscape mode. See the example to catch the player events.
