### ISSUE TITLE
FullScreen Issue

### ISSUE THREAD

**Issue by Rinkubirwal** [darwin-morocho/flutter-meedu-player#5]
when i fullscreen the player it full screen in potrait mode not in lanscape. please helpme.

**Comment by darwin-morocho** [comment]
> when i fullscreen the player it full screen in potrait mode not in lanscape. please helpme.

Some videos in fullscreen mode requires portrait. So yo can listen the player events and detect when the player changes to fullscreen and rotate the device to lanscape mode. See the example to catch the player events.

**Comment by darwin-morocho** [comment]
> > when i fullscreen the player it full screen in potrait mode not in lanscape. please helpme.
> 
> Some videos in fullscreen mode requires portrait. So yo can listen the player events and detect when the player changes to fullscreen and rotate the device to lanscape mode. See the example to catch the player events.

Please update to version 0.1.1
